# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b991d13c-0085-4988-95b8-2dd95a999085";
    fsType = "ext4";
    options = [ "x-gvfs-show" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E5E9-177D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/ssd2" = {
    label = "ssd2";
    fsType = "ext4";
    device = "/dev/disk/by-uuid/a6d24f19-006f-4fbd-9c68-12fd207bca62";
    options = [
      "nofail"
      "x-gvfs-show"
    ];
  };

  fileSystems."/mnt/hdd" = {
    label = "hdd";
    fsType = "btrfs";
    device = "/dev/disk/by-uuid/78992061-e44e-47c4-bcb9-fc2935b5d710";
    options = [
      "nofail"
      "x-gvfs-show"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/91a7b259-ee6b-4cd4-9c73-6331881ef85f";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
