"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$username$directory$git_branch$character"

[line_break]
disabled = true

[username]
show_always = true
format = "[$user]($style) "

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
